const SUITS = {
  Workshop:   { color: '#C2571A', label: 'Workshop' },
  Protocol:   { color: '#1D4ED8', label: 'Protocol' },
  Platform:   { color: '#059669', label: 'Platform' },
  Tool:       { color: '#7C3AED', label: 'Tool' },
  Touchstone: { color: '#B91C1C', label: 'Touchstone' },
};

const CARDS = [
  { id: 'workshop-history-and-genre',    suit: 'Workshop',   name: 'History and Genre',     image: '../images/cards/workshop-history-and-genre.jpg' },
  { id: 'platform-the-exchange',         suit: 'Platform',   name: 'The Exchange',           image: '../images/cards/platform-the-exchange.jpg' },
  { id: 'touchstone-past-and-present',   suit: 'Touchstone', name: 'Past and Present',       image: '../images/cards/touchstone-past-and-present.jpg' },
  { id: 'touchstone-connectivities',     suit: 'Touchstone', name: 'Connectivities',         image: '../images/cards/touchstone-connectivities.jpg' },
  { id: 'touchstone-mediating-technologies', suit: 'Touchstone', name: 'Mediating Technologies', image: '../images/cards/touchstone-mediating-technologies.png' },
  { id: 'protocol-stuckness',            suit: 'Protocol',   name: 'Stuckness',              image: '../images/cards/protocol-stuckness.jpg' },
  { id: 'protocol-mediation',            suit: 'Protocol',   name: 'Mediation',              image: '../images/cards/protocol-mediation.jpg' },
  { id: 'protocol-protocol',             suit: 'Protocol',   name: 'Protocol',               image: '../images/cards/protocol-protocol.png' },
  { id: 'protocol-platform',             suit: 'Protocol',   name: 'Platform',               image: '../images/cards/protocol-platform.jpg' },
  { id: 'protocol-fiction',              suit: 'Protocol',   name: 'Fiction',                image: '../images/cards/protocol-fiction.jpg' },
  { id: 'protocol-better-explanation',   suit: 'Protocol',   name: 'Better Explanation',     image: '../images/cards/protocol-better-explanation.png' },
  { id: 'workshop-heterochrony',         suit: 'Workshop',   name: 'Heterochrony',           image: '../images/cards/workshop-heterochrony.jpg' },
  { id: 'workshop-breaking-boundaries',  suit: 'Workshop',   name: 'Breaking Boundaries',    image: '../images/cards/workshop-breaking-boundaries.jpg' },
  { id: 'workshop-dedisciplinarity',     suit: 'Workshop',   name: 'Dedisciplinarity',       image: '../images/cards/workshop-dedisciplinarity.jpg' },
  { id: 'workshop-the-universal-library',suit: 'Workshop',   name: 'The Universal Library',  image: '../images/cards/workshop-the-universal-library.jpg' },
  { id: 'workshop-trust',                suit: 'Workshop',   name: 'Trust',                  image: '../images/cards/workshop-trust.jpg' },
  { id: 'platform-table',                suit: 'Platform',   name: 'Table',                  image: '../images/cards/platform-table.jpg' },
  { id: 'workshop-visualization',        suit: 'Workshop',   name: 'Visualization',          image: '../images/cards/workshop-visualization.jpg' },
  { id: 'workshop-simulation',           suit: 'Workshop',   name: 'Simulation',             image: '../images/cards/workshop-simulation.jpg' },
  { id: 'workshop-thought-experiment',   suit: 'Workshop',   name: 'Thought Experiment',     image: '../images/cards/workshop-thought-experiment.jpg' },
  { id: 'platform-interface',            suit: 'Platform',   name: 'Interface',              image: '../images/cards/platform-interface.jpg' },
  { id: 'platform-program',             suit: 'Platform',   name: 'Program',                image: '../images/cards/platform-program.jpg' },
  { id: 'platform-network',             suit: 'Platform',   name: 'Network',                image: '../images/cards/platform-network.jpg' },
  { id: 'tool-frame-2',                  suit: 'Tool',       name: 'Frame 2',                image: '../images/cards/tool-frame-2.jpg' },
  { id: 'tool-connectivity',             suit: 'Tool',       name: 'Connectivity',           image: '../images/cards/tool-connectivity.jpg' },
  { id: 'tool-complete-knowledge',       suit: 'Tool',       name: 'Complete Knowledge',     image: '../images/cards/tool-complete-knowledge.jpg' },
  { id: 'tool-frame-1',                  suit: 'Tool',       name: 'Frame 1',                image: '../images/cards/tool-frame-1.jpg' },
  { id: 'tool-when-in-doubt-scale',      suit: 'Tool',       name: 'When in Doubt, Scale!',  image: '../images/cards/tool-when-in-doubt-scale.jpg' },
  { id: 'tool-wandering',                suit: 'Tool',       name: 'Wandering',              image: '../images/cards/tool-wandering.jpg' },
  { id: 'tool-zone',                     suit: 'Tool',       name: 'Zone',                   image: '../images/cards/tool-zone.jpg' },
  { id: 'tool-writing',                  suit: 'Tool',       name: 'Writing',                image: '../images/cards/tool-writing.jpg' },
  { id: 'protocol-re',                   suit: 'Protocol',   name: 'RE:',                    image: '../images/cards/protocol-re.jpg' },
  { id: 'touchstone-the-specific',       suit: 'Touchstone', name: 'The Specific',           image: '../images/cards/touchstone-the-specific.jpg' },
  { id: 'workshop-the-abstract',         suit: 'Workshop',   name: 'The Abstract',           image: '../images/cards/workshop-the-abstract.jpg' },
  { id: 'workshop-embodiment',           suit: 'Workshop',   name: 'Embodiment',             image: '../images/cards/workshop-embodiment.jpg' },
  { id: 'workshop-unity',                suit: 'Workshop',   name: 'Unity',                  image: '../images/cards/workshop-unity.jpg' },
];

// Group cards by suit
Object.keys(SUITS).forEach(suit => { SUITS[suit].cards = []; });
CARDS.forEach(card => SUITS[card.suit].cards.push(card));
